### ISSUE TITLE
Невозможно создать мир с именем, удалённым раннее

### ISSUE THREAD

**Issue by Dymeth** [Slomix/ParkourBeat#24]
Если создать мир, затем удалить его, а после попытаться создать мир с таким же названием, то в консоли возникнет большое количество исключений:
![image](https://github.com/Slomix/ParkourBeat/assets/21080646/ce9c87f9-0752-461e-a910-605b2c27b2f8)

Если перезагрузить плагин после создания мира или после удаления мира, то второй раз мир создаётся без проблем.
При этом на проблему абсолютно не влияет, находились ли игроки в мире в момент удаления или нет

**Comment by Dymeth** [comment]
Предположения:
![image](https://github.com/Slomix/ParkourBeat/assets/21080646/d0639798-38dd-480e-8c4a-9821bd1ee95e)

**Comment by Dymeth** [comment]
Выяснилось, что папки уровней `xxx` и `xxxx` внутри worlds вообще не создались (уровни не удалялись).

Так что для начала необходимо просто протестировать создание уровней, возможно после вынеса в асинхрон что-то сломалось

**Comment by Dymeth** [comment]
![image](https://github.com/Slomix/ParkourBeat/assets/21080646/e55b292c-eaff-4236-9038-1e7f9efbd263)

**Comment by DrupalDoesNotExists** [comment]
Кажется сервер не закрывает файлы миров, а держит их открытыми в своеобразном кэше?

**Comment by Dymeth** [comment]
> Кажется сервер не закрывает файлы миров, а держит их открытыми в своеобразном кэше?

Это была первая моя версия. Однако пришел к выводу, что проблема именно в плагине, поскольку:
1) Проблема решается перезагрузкой плагина между операциями создания/удаления
2) С точки зрения ядра миры вообще каждый раз разные, поскольку при создании каждого нового мира используется случайный UUID 

Есть вариант, что этот самый UUID не выгружается из какого-то кэша при удалении мира. И при попытке создать новый мир используется именно он, а не новый рандомный

**Comment by Dymeth** [comment]
После нескольких багфиксов проблема была решена
