### ISSUE TITLE
Можно редактировать уровень, на котором играют игроки

### ISSUE THREAD

**Issue by Dymeth** [Slomix/ParkourBeat#29]
Необходимо запретить редактирование уровня, пока на нём есть хотя бы один игрок.
Помимо этого, необходимо запретить игрокам начинать игру на уровнях, которые в данный момент редактируются

**Comment by DrupalDoesNotExists** [comment]
Почему нельзя проводить редактирование в отдельном мире-копии?

**Comment by Dymeth** [comment]
> Почему нельзя проводить редактирование в отдельном мире-копии?

Сейчас необходимо быстро и эффективно избавиться от данной проблемы - это самый простой способ.
В перспективе можно будет реализовать одно из альтернативных решений, когда в этом действительно появится нужда

**Comment by Dymeth** [comment]
Проблема исправлена
