### ISSUE TITLE
Точки в режиме редактора добавляются до старта и после финиша

### ISSUE THREAD

**Issue by Dymeth** [Slomix/ParkourBeat#32]
Стоит запретить это делать. При этом можно выводить сообщение в духе
`Скорректируйте старт/финиш, если хотите установить точку в этом месте`

**Comment by DrupalDoesNotExists** [comment]
Как дополнение: стоит вообще запретить ставить точки за последней точкой на пути. В том плане, что если последняя точка пути установлена на текущий момент на Z=100, то ещё 1 точку на Z=100 или на Z=10 уже установить не получится.

Это должно устранить возможность создавать пути, которые идут назад или требуют движения только вбок, т.к. такие моменты просто не пройти.

**Comment by Dymeth** [comment]
Исправлено
