### ISSUE TITLE
Реализовать систему активностей игроков

### ISSUE THREAD

**Issue by Dymeth** [Slomix/ParkourBeat#34]
Система позволит более удобно работать с событиями, а также исключит возможность некорректных состояний в разных менеджерах.
Допустимые состояния:
- Играет
- Наблюдает
- Редактирует уровень

**Comment by DrupalDoesNotExists** [comment]
Вообще создаётся ощущение, что в коде уже слишком много "менеджеров". Возможно стоило заместить эти менеджеры каким-то одним, который давал бы доступ к хорошо прописанному врапперу со всей нужной доп. информацией.

Ну или сделать это даже не менеджером, а просто фабрикой с названием наподобие PlayerWrapperFactory и прикрутить к ней кэш (для любителей паттернов, да здравствует условный CachedPlayerWrapperFactoryProxy!). Для кэша можно использовать обычную мапу (если пока это не вызывает проблем), а если надо попроизводительнее - можно условный Caffeine или EHCache подключить.

**Comment by Dymeth** [comment]
> Вообще создаётся ощущение, что в коде уже слишком много "менеджеров". Возможно стоит заместить эти менеджеры каким-то одним, который давал бы доступ к хорошо прописанному врапперу со всей нужной доп. информацией.
> 
> Ну или сделать это даже не менеджером, а просто фабрикой с названием наподобие PlayerWrapperFactory и прикрутить к ней кэш (для любителей паттернов, да здравствует условный CachedPlayerWrapperFactoryProxy!). Для кэша можно использовать обычную мапу (если пока это не вызывает проблем), а если надо попроизводительнее - можно условный Caffeine или EHCache подключить.

Основа реализована, однако улучшающие пулл-реквесты приветствуются
