### ISSUE TITLE
Избавиться от загрузки мира при необходимости получить UUID владельца

### ISSUE THREAD

**Issue by Dymeth** [Slomix/ParkourBeat#35]
Сейчас для проверки владения уровнем прогружается мир полностью, хотя стоило бы прогружать только его мета-данные один раз при запуске сервера (+ при создании мира)

**Comment by DrupalDoesNotExists** [comment]
Как я упоминал в [своём ответе на #36](https://github.com/Slomix/ParkourBeat/issues/36#issuecomment-1978511220), кажется, что для таких задач уже целесообразно использовать какую-то простейшую базу данных. Иначе мы просто будем "писать свою" внутри плагина.

**Comment by Dymeth** [comment]
> Как я упоминал в [своём ответе на #36](https://github.com/Slomix/ParkourBeat/issues/36#issuecomment-1978511220), кажется, что для таких задач уже целесообразно использовать какую-то простейшую базу данных. Иначе мы просто будем "писать свою" внутри плагина.

В данной задаче идёт речь про организацию бизнес-логики, а не про способ хранения и загрузки данных.
Именно эта задача и была решена в рамках данного issue. Теперь данные уровней на загружаются и не выгружаются без реальной необходимости.
При этом легковестные мета-данные **всех** уровней теперь загружаются при запуске плагина, поскольку они всегда нужны "на горячую" в рантайме - например, для таб-комплита команды /play

Что касается самого хранения данных, то по нему при желании всегда можно создать отдельный issue. Задача будет заключаться в том, чтобы написать новую имплементацию интерфейса [LevelSettingDAO](https://github.com/Slomix/ParkourBeat/blob/main/src/main/java/ru/sortix/parkourbeat/levels/dao/LevelSettingDAO.java).

Но я считаю, что на текущий момент острой необходимости в этом нет. Тем более, что миры по-прежнему нет возможности хранить в базах данных (см. issue со [SlimeWorldManager](https://github.com/Slomix/ParkourBeat/issues/7)).

Поскольку текущая задача выполнена в полном объёме - закрываю
