### ISSUE TITLE
Меню выбора уровня для команд /delete, /edit, /play и /tptoworld

### ISSUE THREAD

**Issue by Dymeth** [Slomix/ParkourBeat#36]
Сейчас перечисленные команды требуют указания текстового названия. А текстовые названия могут пересекаться. В итоге имеем ограничение для пользователей и не очень удобный интерфейс.

Введение меню решит обе проблемы, а также позволит отображать дополнительную информацию об уровне:
- ник создателя
- сложность
- продолжительность

В перспективе:
- рейтинговая ли карта
- оценка пользователей

При этом информацию обо всех уровнях будет необходимо подгружать автоматически при запуске плагина, скорее всего асинхронно в фоновом режиме.

Естественно, должно быть два вида меню:
- с собственными уровнями (открывается при помощи /delete и /edit)
- с абсолютно всеми уровнями (открывается при помощи /play и /tptoworld)

**Comment by DrupalDoesNotExists** [comment]
Кажется, что задача уже больше требует какого-то рода простейшей базы данных, чтобы выполнять поиски с фильтрацией.

**Comment by Dymeth** [comment]
> Кажется, что задача уже больше требует какого-то рода простейшей базы данных, чтобы выполнять поиски с фильтрацией.

Это задача не по загрузке данных, а исключительно по интерфейсу. Если нужно обсудить загрузку - лучше это сделать в #35 или создать новую задачу

**Comment by Dymeth** [comment]
Основа для меню /play реализована

**Comment by Dymeth** [comment]
Меню для всех необходимых команд тоже реализованы, по поводу дополнительной информации созданы отдельные задачи:
- #67 
- #68
- #69
- #70
