### ISSUE TITLE
Реализовать границы уровня

### ISSUE THREAD

**Issue by AlliSite** [Slomix/ParkourBeat#59]
Граница должна быть размером в чанк.
Возьмём демонстрацию дефолтного уровня, который создается
при создании нового уровня
![image](https://github.com/Slomix/ParkourBeat/assets/122743694/cec56e8f-1c69-431d-a976-66dbcdd4b6eb)
Эти стенки были специально построены, чтобы за ними нельзя было строить, и они идеально
совпадают в размер чанка

16 блоков в ширину, это кажется мало, но на самом деле нет, это очень много и достаточно (понять
можно по 113 прохождениях уровней старого пб в ютубе).

Когда строитель попытается выйти за границы, его откинет назад и будет звук фаербола
Если игрок попытается выйти за границы каким-то чудным образом, то он моментально
проиграет

За границами нельзя строить, и спавнить блоки даже через WorldEdit
Высота неограниченная

Борьба с читерами (которые могут легко быть за границами уровня с помощью АКБ): Когда игрок находится за границами уровня 5-10 секунд, его телепортирует на спавн уровня. Но и тут мы находим уязвимость - а что если, точка спауна установлена неккоректно (или в небе) или вовсе не установлена? В таком случае телепортируем его в середину чанка, в котором он находится

**Comment by Dymeth** [comment]
Строительство за пределами уровня уже давно ограничено.

WE пока нет, но когда будет вводиться - будет вводиться сразу с указанными ограничениями, issue по этому вопросу: https://github.com/Slomix/ParkourBeat/issues/56

По поводу откидывания от стенок - это будет реализовано кастомными блоками от witwar: https://discord.com/channels/1079842075853459526/1226871880196165733

Технической необходимости в запрете полётов в пустые чанки нет. Нагрузки от этого минимум. Единственная проблема - это сохранение пустых чанков на диск, но это тоже будет решаться в рамках отдельной задачи:
https://discord.com/channels/1079842075853459526/1226871880196165733
