### ISSUE TITLE
Нужен предмет для сброса всех точек в мире

### ISSUE THREAD

**Issue by Dymeth** [Slomix/ParkourBeat#61]
Уже неоднократно требовалась эта функция разным людям

**Comment by Assasain26** [comment]
Хороший предмет. На счёт инвентаря -> 36 слотов, что означает нет слотов?
+ Все предметы можно вкомпоновать в другие предметы, типо тот же компас -> Он же имеет в себе ещё предметы, которые называется головами и т.д.
Команды можно оставить, для опытных пользователей, но предмет должен быть реализован

**Comment by AlliSite** [comment]
> Хороший предмет. На счёт инвентаря -> 36 слотов, что означает нет слотов?
> 
> * Все предметы можно вкомпоновать в другие предметы, типо тот же компас -> Он же имеет в себе ещё предметы, которые называется головами и т.д.
>   Команды можно оставить, для опытных пользователей, но предмет должен быть реализован
![image](https://github.com/Slomix/ParkourBeat/assets/122743694/cf63e8f9-1b83-4ff6-b228-697e631eed5d)
POV

**Comment by Dymeth** [comment]
> В инвентаре уже скоро не останется места даже для инструментов, можно такие технические функции поместить в команды.

Предмет добавлен внутрь меню "Параметры уровня"
