### ISSUE TITLE
Поддержка SlimeWorldManager

### ISSUE THREAD

**Issue by Dymeth** [Slomix/ParkourBeat#7]
Нам необходимо перейти на SlimeWorldManager для достижения решения следующих задач:
1) Загрузка миров в ОЗУ без влияния на производительность (не в основном серверном потоке)
2) Сокращение потребления места на диске на хранение пользовательских миров

Подробности о SWM:
https://www.spigotmc.org/resources/69974
https://github.com/cijaaimee/Slime-World-Manager

Доказательство проблем с производительностью при использовании Bukkit.createWorld():
![image](https://github.com/Slomix/ParkourBeat/assets/21080646/fd5ff288-04c5-48da-a4d1-877a6214f07c)

**Comment by DrupalDoesNotExists** [comment]
I guess It's better to use some specific implementation that supports async from the box, maybe something like AsyncSlimeWorldManager.

**Comment by Dymeth** [comment]
Есть очень большие сомнения о необходимости использовать SWM, с ним есть сложности.

Оригинальный плагин SlimeWorldManager заброшен 4 года назад, его разработчики рекомендуют использовать Advanced SlimeWorldManager (он же AdvancedSlimePaper):
https://spigotmc.org/resources/87209
https://github.com/InfernalSuite/AdvancedSlimePaper

AdvancedSlimePaper - это не просто плагин, это полноценный форк Paper. В итоге мы имеем несколько проблем:

1) Мы принуждаем пользователей использовать сторонний софт вместо того ядра, которое они выбрали самостоятельно. Это как минимум неудобно, а как максимум небезопасно.

2) Данный форк содержит сомнительные патчи. Если бы патчи были действительно качественными - их бы приняли в сам Paper в качестве альтернативного способа прогрузки миров. Но, скорее всего, в Paper даже не предлагали PR, поскольку в патчах имеются, например, вот такие странные участки:
https://github.com/InfernalSuite/AdvancedSlimePaper/blob/dc112775adc988eac54444a215ab055a41a538f9/patches/api/0002-Dont-close-Slime-Plugin-Classloader.patch#L15

3) Последний релиз AdvancedSlimePaper работает только на версии Minecraft 1.20.4. Более старые релизы находятся ещё в одном репозитории, который тоже был заброшен в районе двух лет назад: https://github.com/Paul19988/Advanced-Slime-World-Manager/releases
Поначалу кажется, что это не критично. Но в случае изменения апи в актуальной версии AdvancedSlimePaper мы получим ряд проблем

**Comment by Dymeth** [comment]
Ускорить создание (загрузку) миров через баккит удалось ускорить в 7 раз при помощи `world.setKeepSpawnInMemory(false)` в WorldInitEvent.
Помимо этого, сейчас при создании миров в основном потоке выполняется копирование файлов и папок через NIO. Если вынести этот процесс в отдельный поток - это ещё больше ускорить процесс создания (загрузки) миров.

Поэтому на данном этапе считаю использование SlimeWorldManager нецелесообраным

**Comment by Dymeth** [comment]
С прогрузкой нет проблем и без SlimeWorldManager. Теперь грузится по 500 миров в секунду при необходимости.
Если и будем переходить, то явно не в ближайшем будущем

**Comment by Dymeth** [comment]
Немного больше информации по вопросу:
https://github.com/PaperMC/Paper/issues/8761
https://github.com/xymb-endcrystalme/LinearPaper
