### ISSUE TITLE
Хранить название миров в UUID.

### ISSUE THREAD

**Issue by Slomix** [Slomix/ParkourBeat#9]
Сейчас все миры хранятся с названием который им дал игрок, в таком случае мы получаем две проблемы:
1. Игрок не может создать мир с названием lobby или world. (В целом не критично, но все же)
2. Игрок может использовать в названии мира некорректные символы, ограничивать его в этом тоже не охота.
Можно хранить оригинальное название уровня в настройках вместе с его же UUID. Правда тогда в при загрузке сервера нам бы как то узнать какому имени соответствует какой UUID, например кэшировать названия всех уровней и их UUID.

**Comment by Dymeth** [comment]
Поскольку в папке с мирами находятся и другие пользовательские миры - предлагаю хранить все миры в формате:
`pd_<UUID>`
